server:
  port: 8080

app:
  datasources:
    ms_upload_arquivos:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/upload_files?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD}
      maximum-pool-size: 10
      minimum-idle: 5
  watch:
    directory: /caminho/para/pasta/upload 
  datasources:
    ms_upload_arquivos:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/upload_files?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD}
      maximum-pool-size: 10
      minimum-idle: 5

logging:
  level:
    br.com.cantarutti: DEBUG

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB